[package]
name = "day_fifteen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mkagie_utils = { path = "../mkagie_utils" }
petgraph = "0.6.0"