[package]
name = "day_twenty-two"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mkagie_utils = { path = "../mkagie_utils" }
ndarray = "0.15.4"
dashmap = "5.0.0"
threadpool = "1.8.1"